### ISSUE TITLE
Math_Vec#F_t is undefined type

### ISSUE THREAD

**Issue by thomatoes50** [DeanoC/al2o3_vfile#1]
i could not find any definition anywhere even in al2o3_cmath

**Comment by DeanoC** [comment]
Hey.
Oops my ide forgot to update that library when i removed the _t postfix. Updated manually now. 
The types are
Math_Vec#F now and vfile utils has been updated.

**Comment by thomatoes50** [comment]
thanks, you should check in other libraries.
I saw it else where (gfx_meshmod, gfx_meshmodio, ...)
